#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# JReversePro - startup script

# if JREVERSE_HOME is not set, use dirname to get at it
if [ "z$JREVERSE_HOME" = "z" ] ; then
   DIRNAME=`dirname $0`
   JREVERSE_HOME=`cd $DIRNAME/..; pwd`
fi

# get our java from JAVA_HOME if set, otherwise
# from classpath
if [ "z$JAVA_HOME" != "z" ]; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA="java"
fi

CP=$JREVERSE_HOME/target/jreversepro-1.5.0.jar
# add libs to CLASSPATH
for f in $JREVERSE_HOME/lib/*.jar; do
  CP=${CP}:$f;
done

exec $JAVA -classpath $CP org.jreversepro.cmd.CommandMain $@

